import { Navbar } from "@/src/components/navigation/Navbar";
import "./globals.css";
import { AmbientMusic } from "@/src/components/audio/AmbientMusic";
import { getDriveUrl } from "@/src/lib/drive";
import { MEDIA } from "@/src/constants/media";

export const metadata = {
  title: "Argentina Road Experience",
  description: "Discover Argentina by road. A premium bus travel experience.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased bg-background text-foreground">
        <Navbar />
        <AmbientMusic src="https://res.cloudinary.com/dpadnzbyw/video/upload/v1768092118/audio_rikhxp.mp3" />

        {children}
      </body>
    </html>
  );
}


  // import type { Metadata } from "next";
  // import { Geist, Geist_Mono } from "next/font/google";
  // import "./globals.css";
  
  // const geistSans = Geist({
  //   variable: "--font-geist-sans",
  //   subsets: ["latin"],
  // });
  
  // const geistMono = Geist_Mono({
  //   variable: "--font-geist-mono",
  //   subsets: ["latin"],
  // });
  
  // export const metadata: Metadata = {
  //   title: "Create Next App",
  //   description: "Generated by create next app",
  // };
  
  // export default function RootLayout({
  //   children,
  // }: Readonly<{
  //   children: React.ReactNode;
  // }>) {
  //   return (
  //     <html lang="en">
  //       <body
  //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  //       >
  //         {children}
  //       </body>
  //     </html>
  //   );
  // }